source 'ssh://git@github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target :'GraphProfileSample' do
    pod 'PWCore', :path => '/Users/ches/Documents/internal/core-sdk-ios'
end
